### ISSUE TITLE
Allow the user to see every charter under a region on one page

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#512] opened 2016-04-01 20:52 UTC

**Comment by vleong2332** [comment] 2016-04-06 12:53
Duplicate of #497

**Comment by vleong2332** [comment] 2016-04-19 13:07
If I recall correctly, Paul no longer needs this after we showed him how to show 100 charters in WA region detail page. Could you confirm, @Redmayspecial or @markalolo?

**Comment by markalolo** [comment] 2016-04-19 14:02
This is still a requirement because Paul wants to be able to print out all the charters. This won't work if it requires paging.

**Comment by vleong2332** [comment] 2016-04-19 14:21
I wonder if having a "Print" mode will work for this, since his intention is to print it out anyway.

**Comment by markalolo** [comment] 2016-04-19 14:31
Could be? Can we have the "show X entries" include an option for "All"?

**Comment by vleong2332** [comment] 2016-04-19 14:32
Maybe. I'll need to do a bit of research to determine if that's possible.

**Closed** 2016-06-02 12:48 UTC
Labels: HIGH Priority, Question
