### ISSUE TITLE
Add email Field

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#95] opened 2015-07-30 18:08 UTC
_From @jag3773 on June 8, 2015 19:26_

On Request to Publish form, we should add an email field to get the requester's email so that we can keep them updated on the status of their request.

_Copied from original issue: unfoldingWord-dev/uwadmin#27_

**Comment by paltman** [comment] 2015-08-26 19:51
Duplicate of #27

**Closed by paltman** 2015-08-26 19:51 UTC
Labels: Priority, uW Admin
